server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
jwt:
  secret: VnD95F5NHPIgnDuKb6GZl81tM+JZLfPT9TC0s7xyJ2I=
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(%logger{36}){cyan} - %clr(%msg%n){faint}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: logs/api-gateway-%d{yyyy-MM-dd}.%i.log
  level:
    by.kotik: info
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**, /roles/**
              filters:
                - name: AuthFilter
            - id: poll-service
              uri: lb://poll-service
              predicates:
                - Path=/polls/**, /options/**
              filters:
                - name: AuthFilter
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: vote-service
              uri: lb://vote-service
              predicates:
                - Path=/votes/**
              filters:
                - name: AuthFilter
            - id: analytics-service
              uri: lb://analytics-service
              predicates:
                - Path=/analytics/**
              filters:
                - name: AuthFilter

