spring:
  aop:
    proxy-target-class: true
    auto: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: analytics-service
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/poll-system-analytics
    username: postgres
    password: 5409
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(%logger{36}){cyan} - %clr(%msg%n){faint}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/analytics-service.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: logs/analytics-service-%d{yyyy-MM-dd}.%i.log
  level:
    by.kotik: info


