spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: vote-service
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/poll-system-votes
    username: postgres
    password: 5409
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0
jwt:
  secret: VnD95F5NHPIgnDuKb6GZl81tM+JZLfPT9TC0s7xyJ2I=
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
